#include "StdInc.h"
#include "AssetPackageCreator.h"
#include "AssetPreviewResolver.h"
#include "AssetNotification.h"
#include "Logger.h"

#include <filesystem>
#include <fstream>

namespace
{
    std::string SafeName(std::string s)
    {
        for (char& c : s)
        {
            if (c == '\\' || c == '/' || c == ':' || c == '*' || c == '?' || c == '"' || c == '<' || c == '>' || c == '|')
                c = '_';
        }

        if (s.empty())
            s = "NewMod";

        return s;
    }

    std::string Normalize(std::string s)
    {
        std::replace(s.begin(), s.end(), '\\', '/');

        while (!s.empty() && (s[0] == '/' || s[0] == '.'))
            s.erase(s.begin());

        return s;
    }
}

namespace AssetPackageCreator
{
    bool Init()
    {
        std::filesystem::create_directories(GetModsRoot());
        return true;
    }

    void Shutdown()
    {
    }

    std::filesystem::path GetModsRoot()
    {
        return std::filesystem::path(AssetBrowser::GetModsFolder());
    }

    std::filesystem::path CreatePackage(
        const std::string& modName,
        const std::string& author,
        const std::string& description,
        const std::vector<AssetBrowser::AssetEntry>& assets)
    {
        std::filesystem::path root = GetModsRoot() / SafeName(modName);
        std::filesystem::path assetRoot = root / "assets";

        std::filesystem::create_directories(assetRoot);

        std::ofstream meta(root / "mod.json", std::ios::out | std::ios::trunc);
        meta << "{\n";
        meta << "  \"Name\": \"" << modName << "\",\n";
        meta << "  \"Author\": \"" << author << "\",\n";
        meta << "  \"Version\": \"1.0.0\",\n";
        meta << "  \"Description\": \"" << description << "\"\n";
        meta << "}\n";

        std::ofstream readme(root / "readme.txt", std::ios::out | std::ios::trunc);
        readme << modName << "\n";
        readme << "Generated by NS2 Revived Asset Browser V2.\n\n";
        readme << description << "\n";

        int copied = 0;

        for (const auto& asset : assets)
        {
            std::string readable;

            if (!AssetPreviewResolver::ResolveReadablePath(asset, readable, true))
                continue;

            std::filesystem::path rel =
                !asset.ArchiveEntryPath.empty()
                ? Normalize(asset.ArchiveEntryPath)
                : Normalize(asset.VirtualPath);

            std::filesystem::path out = assetRoot / rel;
            std::filesystem::create_directories(out.parent_path());

            std::error_code ec;
            std::filesystem::copy_file(readable, out, std::filesystem::copy_options::overwrite_existing, ec);

            if (!ec)
                copied++;
        }

        Logger::Info("Created mod package: " + root.string() + " assets=" + std::to_string(copied));
        AssetNotification::PushSuccess("Mod Package Created", root.string());

        return root;
    }
}
